# Generated by Django 4.0.3 on 2022-05-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'gender', 'age'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'gender', 'age'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('reldate', models.IntegerField()),
                ('cast', models.ManyToManyField(to='movies.cast')),
                ('director', models.ManyToManyField(to='movies.director')),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['name', 'reldate'],
            },
        ),
    ]
